version: "3"
services:
  api:
    restart: on-failure
    build: .
    depends_on:
      - database
    env_file: .env

    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - api-network

  database:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
